---
username: admin
password: admin 

banner_text: "--Welcome to Onboarding BIGIP--" 

hostname: 'bigip-a.ansible.lab'        

ntp_servers:                                        
 - '172.27.1.1'
 - '172.27.1.2'

dns_servers:                                        
 - '8.8.8.8'
 - '4.4.4.4'

dns_search_domains:                                 
 - 'local'
 - 'localhost'

ip_version: 4                                       

vlan_information:                                   
 - name: 'External'                                 
   tag: '10'
   interface: '1.2'                                 
 - name: 'Internal'                                 
   tag: '11'     
   interface: '1.1'

selfip_information:                                 
 - name: 'External-SelfIP'                                        
   address: '10.1.10.10'                                         
   netmask: '255.255.255.0'
   vlan: 'External'
   allow_service: 'default'
 - name: 'Internal-SelfIP'
   address: '10.1.20.10'
   netmask: '255.255.255.0'
   vlan: 'Internal'
   allow_service: 'default'

module_provisioning:                                 
 - name: 'asm'                                       
   level: 'nominal'

# Service Configuration

pool_name: "web-pool"

vip_name: "http_virtual_server"
vip_port: "80"
vip_ip: "10.1.20.120"

pool_members:
- port: "80"
  host: "10.1.10.100"
