---
- name: UCS Management Tasks
  hosts: 10.1.1.4
  gather_facts: false

  vars:
    username: admin
    password: admin

    bigip: 10.1.1.4

    # action: save
    action: install
    license: yes
    # ucsname: origin.ucs # Default
    ucsname: /var/local/ucs/origin.ucs

  tasks:
#  - name: Upload UCS
#    bigip_ucs:
#      server: "{{ inventory_host }}"
#      user: "{{ username }}"
#      password: "{{ password }}"
#      ucs: "{{ ucsname }}"
#      state: present
#    delegate_to: localhost
    

  - name: Install (upload, install) UCS.
    bigip_ucs:
      server: "{{ bigip }}"
      user: "{{ username }}"
      password: "{{ password }}"
      ucs: "{{ ucsname }}"
      state: installed
    delegate_to: localhost
    when: action == "install"

#  - name: Install (upload, install) UCS without installing the license portion
#    bigip_ucs:
#      server: "{{ inventory_host }}"
#      user: "{{ username }}"
#      password: "{{ password }}"
#      ucs: "{{ ucsname }}"
#      state: installed
#      no_license: yes
#    delegate_to: localhost
#
#  - name: Install (upload, install) UCS except the license, and bypassing the platform check
#    bigip_ucs:
#      server: "{{ inventory_host }}"
#      user: "{{ username }}"
#      password: "{{ password }}"
#      ucs: "{{ ucsname }}"
#      state: installed
#      no_license: yes
#      no_platform_check: yes
#    delegate_to: localhost
#
#  - name: Install (upload, install) UCS using a passphrase necessary to load the UCS
#    bigip_ucs:
#      server: "{{ inventory_host }}"
#      user: "{{ username }}"
#      password: "{{ password }}"
#      ucs: "{{ ucsname }}"
#    state: installed
#    passphrase: MyPassphrase1234
#  delegate_to: localhost
#
#- name: Remove uploaded UCS file
#  bigip_ucs:
#    server: "{{ inventory_host }}"
#    user: "{{ username }}"
#    password: "{{ password }}"
#    ucs: "{{ ucsname }}"
#    state: absent
#  delegate_to: localhost
